-- Piloto PostGIS para RED_VIAL.
-- Fase 1: no reemplaza la lógica JS del worker. Permite comparar resultados
-- espaciales contra la interpolación actual antes de migrar el resto de corredores.
create schema if not exists gis;
create extension if not exists postgis with schema gis;
set search_path = public, gis, extensions;

create table if not exists public.road_corridors (
  id bigint generated by default as identity primary key,
  badge text not null unique,
  name text not null,
  aliases text[] not null default '{}',
  km_start double precision not null,
  km_end double precision not null,
  geom geometry(LineString,4326) not null,
  source text not null default 'RED_VIAL',
  source_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint road_corridors_km_range check (km_end > km_start)
);

create index if not exists road_corridors_geom_gix
  on public.road_corridors using gist (geom);

alter table public.road_corridors enable row level security;
revoke all on public.road_corridors from anon, authenticated;
grant select, insert, update, delete on public.road_corridors to service_role;

create or replace function public.road_corridor_point_at_km(
  p_badge text,
  p_km double precision
)
returns table (
  badge text,
  name text,
  requested_km double precision,
  latitude double precision,
  longitude double precision,
  fraction double precision
)
language sql
stable
security invoker
set search_path = public, gis, extensions
as $$
  select
    c.badge,
    c.name,
    p_km,
    st_y(st_lineinterpolatepoint(c.geom,
      greatest(0::double precision, least(1::double precision,
        (p_km-c.km_start)/nullif(c.km_end-c.km_start,0)
      ))
    )) as latitude,
    st_x(st_lineinterpolatepoint(c.geom,
      greatest(0::double precision, least(1::double precision,
        (p_km-c.km_start)/nullif(c.km_end-c.km_start,0)
      ))
    )) as longitude,
    greatest(0::double precision, least(1::double precision,
      (p_km-c.km_start)/nullif(c.km_end-c.km_start,0)
    )) as fraction
  from public.road_corridors c
  where c.badge=p_badge
    and p_km between c.km_start and c.km_end
  limit 1;
$$;

create or replace function public.road_corridor_nearest(
  p_lat double precision,
  p_lon double precision,
  p_max_meters double precision default 1500
)
returns table (
  badge text,
  name text,
  latitude double precision,
  longitude double precision,
  distance_m double precision,
  estimated_km double precision,
  fraction double precision
)
language sql
stable
security invoker
set search_path = public, gis, extensions
as $$
  with input as (
    select st_setsrid(st_makepoint(p_lon,p_lat),4326) as pt
  ),
  ranked as (
    select
      c.*,
      i.pt,
      st_linelocatepoint(c.geom,i.pt) as frac,
      st_distance(c.geom::geography,i.pt::geography) as meters
    from public.road_corridors c
    cross join input i
    where st_dwithin(c.geom::geography,i.pt::geography,p_max_meters)
    order by meters asc
    limit 1
  )
  select
    r.badge,
    r.name,
    st_y(st_lineinterpolatepoint(r.geom,r.frac)) as latitude,
    st_x(st_lineinterpolatepoint(r.geom,r.frac)) as longitude,
    r.meters as distance_m,
    r.km_start + ((r.km_end-r.km_start)*r.frac) as estimated_km,
    r.frac as fraction
  from ranked r;
$$;

revoke all on function public.road_corridor_point_at_km(text,double precision) from public, anon, authenticated;
revoke all on function public.road_corridor_nearest(double precision,double precision,double precision) from public, anon, authenticated;
grant execute on function public.road_corridor_point_at_km(text,double precision) to service_role;
grant execute on function public.road_corridor_nearest(double precision,double precision,double precision) to service_role;

-- Corredores piloto: México–Querétaro y Querétaro–Irapuato.
insert into public.road_corridors (badge,name,aliases,km_start,km_end,geom,source,source_version)
values ('mex-qro','México–Querétaro',ARRAY['mexico-queretaro','mexico queretaro','queretaro-mexico','queretaro mexico','mex-57d','57d']::text[],43,148,
  st_geomfromtext('LINESTRING(-99.1333 19.432,-99.1339 19.4336,-99.133 19.4416,-99.134 19.4481,-99.137 19.4493,-99.1383 19.4551,-99.1375 19.4645,-99.1363 19.4683,-99.137 19.4709,-99.1395 19.4767,-99.1471 19.4961,-99.1514 19.5052,-99.1592 19.5035,-99.1739 19.508,-99.1766 19.5136,-99.1788 19.525,-99.1824 19.5428,-99.1858 19.5585,-99.1933 19.56,-99.2047 19.5645,-99.208 19.5707,-99.208 19.5755,-99.2045 19.5842,-99.2015 19.5897,-99.2012 19.5956,-99.1919 19.598,-99.1885 19.6015,-99.1908 19.6158,-99.1917 19.6209,-99.1977 19.6561,-99.2055 19.7035,-99.2102 19.7318,-99.2141 19.7549,-99.2176 19.776,-99.2275 19.7913,-99.2369 19.8079,-99.2482 19.8252,-99.2707 19.8345,-99.2837 19.8484,-99.3239 19.8662,-99.344 19.8882,-99.3499 19.9052,-99.3754 19.9262,-99.3891 19.9433,-99.4113 19.9553,-99.424 19.9636,-99.4354 19.9735,-99.4399 19.9844,-99.4885 19.9978,-99.5352 20.0262,-99.5646 20.0376,-99.5844 20.047,-99.6042 20.0699,-99.6265 20.0829,-99.6498 20.0804,-99.6847 20.0898,-99.6998 20.1063,-99.7244 20.1244,-99.7527 20.1655,-99.7891 20.2084,-99.8406 20.2504,-99.9 20.28,-99.9279 20.2958,-99.935 20.3044,-99.9346 20.3254,-99.9471 20.3449,-99.9727 20.3629,-99.9913 20.3726,-100.0083 20.3774,-100.0222 20.3957,-100.0425 20.4149,-100.0661 20.4346,-100.0801 20.4485,-100.1117 20.4791,-100.139 20.502,-100.1572 20.5122,-100.1813 20.5298,-100.2251 20.5589,-100.2494 20.5674,-100.2669 20.5718,-100.3049 20.5697,-100.3347 20.5756,-100.3431 20.5846,-100.3517 20.5882,-100.3653 20.5814,-100.382 20.578,-100.3866 20.5803,-100.3887 20.5859,-100.3898 20.5888,-100.3915 20.5924)',4326),'RED_VIAL estática','pilot-2026-09-22')
on conflict (badge) do update set
  name=excluded.name,
  aliases=excluded.aliases,
  km_start=excluded.km_start,
  km_end=excluded.km_end,
  geom=excluded.geom,
  source=excluded.source,
  source_version=excluded.source_version,
  updated_at=now();

insert into public.road_corridors (badge,name,aliases,km_start,km_end,geom,source,source_version)
values ('qro-irp','Querétaro–Irapuato',ARRAY['queretaro-irapuato','irapuato-queretaro','queretaro irapuato','irapuato queretaro','mex-45d','45d']::text[],0,104,
  st_geomfromtext('LINESTRING(-100.3915 20.5924,-100.3923 20.5935,-100.395 20.5925,-100.3969 20.5908,-100.3968 20.5877,-100.3965 20.5865,-100.3958 20.5841,-100.3962 20.5831,-100.3978 20.5821,-100.3989 20.5811,-100.3995 20.5805,-100.4023 20.5772,-100.4032 20.5771,-100.4042 20.5772,-100.4062 20.5769,-100.4396 20.5763,-100.4475 20.5754,-100.464 20.5733,-100.4729 20.5722,-100.48 20.5713,-100.4959 20.5684,-100.5047 20.5668,-100.5109 20.5656,-100.5175 20.5644,-100.5523 20.5579,-100.5697 20.5547,-100.579 20.5505,-100.5918 20.5444,-100.6151 20.5332,-100.6271 20.5324,-100.6481 20.5323,-100.6689 20.5321,-100.6744 20.5332,-100.6951 20.5379,-100.7176 20.5345,-100.7189 20.5346,-100.7255 20.5381,-100.7368 20.544,-100.7492 20.5468,-100.7643 20.5518,-100.7892 20.5546,-100.8221 20.558,-100.8831 20.5685,-100.9031 20.5719,-100.9446 20.5768,-100.9759 20.5793,-100.9882 20.5803,-101.0053 20.5827,-101.0173 20.5844,-101.0306 20.5862,-101.039 20.5874,-101.0472 20.588,-101.0575 20.5883,-101.0853 20.5891,-101.1098 20.5897,-101.1334 20.5903,-101.1408 20.5906,-101.1519 20.5928,-101.18 20.5984,-101.1816 20.5987,-101.2058 20.6035,-101.2092 20.6045,-101.2199 20.6113,-101.2357 20.6215,-101.2478 20.6292,-101.262 20.6384,-101.2829 20.6507,-101.2892 20.6544,-101.2914 20.6549,-101.2973 20.6545,-101.2994 20.6553,-101.3015 20.6567,-101.3045 20.6594,-101.3068 20.6607,-101.3131 20.6621,-101.3176 20.663,-101.3232 20.6641,-101.3262 20.6652,-101.3292 20.6673,-101.3294 20.6667,-101.3303 20.6657,-101.3334 20.6663,-101.3371 20.6671,-101.3388 20.6676,-101.3393 20.6674,-101.3461 20.6679,-101.3492 20.6693,-101.3499 20.6705,-101.3508 20.6733,-101.3513 20.6751,-101.3519 20.676)',4326),'RED_VIAL estática','pilot-2026-09-22')
on conflict (badge) do update set
  name=excluded.name,
  aliases=excluded.aliases,
  km_start=excluded.km_start,
  km_end=excluded.km_end,
  geom=excluded.geom,
  source=excluded.source,
  source_version=excluded.source_version,
  updated_at=now();

-- Pruebas manuales sugeridas:
-- select * from public.road_corridor_point_at_km('mex-qro', 51);
-- select * from public.road_corridor_nearest(19.60, -99.19, 3000);
